version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file: .env
    image: mariadb
    networks:
      - rezo
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped




networks:
  rezo:

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/zminhas/data/database
      type: volume
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/zminhas/data/wordpress
      type: volume
      o: bind

