version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    image: mariadb
    restart: unless-stopped
    networks:
      - inception_network
    volumes:
      - mariadb-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER", "-p$MARIADB_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    image: wordpress
    restart: unless-stopped
    networks:
      - inception_network
    volumes:
      - wordpress-volume:/var/www/html


networks:
  rezo:

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/zminhas/data/database
      type: volume
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/zminhas/data/wordpress
      type: volume
      o: bind

