version: "3.9"
services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file: .env
    image: mariadb
    volume: mariadb_volume:/var/lib/mysql
    network: rezo
    restart: unless-stopped

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/zminhas/data/database
      type: volume
      o: bind

networks:
  rezo:
