version: "3.9"
services:
  mariadb:
    build: ./mariadb
    image: "mariadb"
    container_name: "mariadb"
    volume: mariadb_volume
    network: rezo

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/zminhas/data/database
      type: volume
      o: bind

networks:
  rezo:
