version: "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file: .env
    image: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks: 
      - rezo
    restart: unless-stopped

networks:
  rezo:

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: /home/zminhas/data/database
      type: volume
      o: bind
